/****************************************************************************
** Generated by HaiQ
**
** Project name:  fmseg
** Project date:  Mon Aug 11 2014
** Author: 
****************************************************************************/
#include <QApplication>
#include <QWidget>
#include "fmsegwidget.h"
#include <math.h>
#include "jniftiimage2.h"
#include <QFileInfo>
#include <QDebug>
#include <QStringList>

///////////////////////////////// ** ////////////////////////////////////
int main(int argc, char *argv[])
{
	QApplication app(argc, argv);
	
	Array3D X,M;	
	
	QStringList args;
	for (int i=1; i<argc; i++) {
		QString tmp=argv[i];
		if (!tmp.isEmpty()) args << tmp;
	}
	
	if (args.count()<1) {
		X.allocate(256,256,3);
		M.allocate(256,256,3);
		for (int z=0; z<X.N3(); z++)
		for (int y=0; y<X.N2(); y++)
		for (int x=0; x<X.N1(); x++) {
			float r=sqrt((x-X.N1()/2)*(x-X.N1()/2)+(y-X.N2()/2)*(y-X.N2()/2));
			X.setValue(r,x,y,z);
			if (r<=10) M.setValue(1,x,y,z);
		}
	}
	else {
		if ((QFileInfo(argv[1]).suffix()=="nii")||(QFileInfo(argv[1]).suffix()=="hdr")||(QFileInfo(argv[1]).suffix()=="img")) {
			JNiftiImage2 NI;
			NI.read(argv[1]);
			X=NI.dataXYZ(0);
		}
		else if (QFileInfo(argv[1]).suffix()=="mda") {
			X.read(argv[1]);
		}
		else {
			qWarning() << "Unknown file type";
			return -1;
		}
		M.allocate(X.N1(),X.N2(),X.N3());
	}

	FMSegWidget W;
	W.setArray(X);
	W.setMask(M);
	W.refresh();
	W.showNormal();
	W.resize(600,600);

	return app.exec();
}

